<?php
declare(strict_types=1);

// Contentful SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ContentfulUtility::setRegistrar(function (ContentfulUtility $u): void {
    $u->clean = [ContentfulClean::class, 'call'];
    $u->done = [ContentfulDone::class, 'call'];
    $u->make_error = [ContentfulMakeError::class, 'call'];
    $u->feature_add = [ContentfulFeatureAdd::class, 'call'];
    $u->feature_hook = [ContentfulFeatureHook::class, 'call'];
    $u->feature_init = [ContentfulFeatureInit::class, 'call'];
    $u->fetcher = [ContentfulFetcher::class, 'call'];
    $u->make_fetch_def = [ContentfulMakeFetchDef::class, 'call'];
    $u->make_context = [ContentfulMakeContext::class, 'call'];
    $u->make_options = [ContentfulMakeOptions::class, 'call'];
    $u->make_request = [ContentfulMakeRequest::class, 'call'];
    $u->make_response = [ContentfulMakeResponse::class, 'call'];
    $u->make_result = [ContentfulMakeResult::class, 'call'];
    $u->make_point = [ContentfulMakePoint::class, 'call'];
    $u->make_spec = [ContentfulMakeSpec::class, 'call'];
    $u->make_url = [ContentfulMakeUrl::class, 'call'];
    $u->param = [ContentfulParam::class, 'call'];
    $u->prepare_auth = [ContentfulPrepareAuth::class, 'call'];
    $u->prepare_body = [ContentfulPrepareBody::class, 'call'];
    $u->prepare_headers = [ContentfulPrepareHeaders::class, 'call'];
    $u->prepare_method = [ContentfulPrepareMethod::class, 'call'];
    $u->prepare_params = [ContentfulPrepareParams::class, 'call'];
    $u->prepare_path = [ContentfulPreparePath::class, 'call'];
    $u->prepare_query = [ContentfulPrepareQuery::class, 'call'];
    $u->graphql_body = [ContentfulGraphql::class, 'body'];
    $u->graphql_errors = [ContentfulGraphql::class, 'errors'];
    $u->result_basic = [ContentfulResultBasic::class, 'call'];
    $u->result_body = [ContentfulResultBody::class, 'call'];
    $u->result_headers = [ContentfulResultHeaders::class, 'call'];
    $u->transform_request = [ContentfulTransformRequest::class, 'call'];
    $u->transform_response = [ContentfulTransformResponse::class, 'call'];
});
